apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbittorent
spec:
  serviceName: qbittorent
  replicas: 1
  selector:
    matchLabels:
      app: qbittorent
  template:
    metadata:
      labels:
        app: qbittorent
    spec:
      containers:
      - name: qbittorent
        image: qbittorrentofficial/qbittorrent-nox:4.6.7-1
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "100"
        ports:
        - containerPort: 6881
        - containerPort: 8080
        volumeMounts:
        - name: mnt-volume
          mountPath: /mnt
        - name: config-volume
          mountPath: /config
        - name: downloads-volume
          mountPath: /downloads
      volumes:
      - name: mnt-volume
        hostPath:
          path: /mnt  # Path on the host
          type: Directory  # Ensure this is a directory
      - name: config-volume
        hostPath:
          path: /opt/k3s/qbittorent/config  # Path on the host
          type: Directory  # Ensure this is a directory
      - name: downloads-volume
        hostPath:
          path: /opt/k3s/qbittorent/downloads  # Path on the host
          type: Directory  # Ensure this is a directory

