apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emby
spec:
  serviceName: emby
  replicas: 1
  selector:
    matchLabels:
      app: emby
  template:
    metadata:
      labels:
        app: emby
    spec:
      nodeSelector:
        node-group: nixos
      containers:
      - name: emby
        image: emby/embyserver:4.9.1.20
        env:
        - name: UID
          value: "1000"
        - name: GID
          value: "100"
        ports:
        - containerPort: 8096
        volumeMounts:
        - name: mnt-volume
          mountPath: /mnt
        - name: config-volume
          mountPath: /config
        - name: download-volume
          mountPath: /downloads
      volumes:
      - name: mnt-volume
        hostPath:
          path: /mnt
          type: Directory
      - name: config-volume
        hostPath:
          path: /opt/k3s/emby/config
          type: DirectoryOrCreate
      - name: download-volume
        hostPath:
          path: /opt/k3s/qbittorrent/downloads
          type: Directory
